### ISSUE TITLE
[UpdateChecker] Cog won't load.

### ISSUE THREAD

**Issue by Dav-Git** [NeuroAssassin/Toxic-Cogs#6]
When trying to load the UpdateChecker cog it throws a big fat error back at me.
![grafik](https://user-images.githubusercontent.com/57032623/72951004-4aa17600-3d8d-11ea-91b4-614a2bd8d5c3.png)

**Comment by Dav-Git** [comment]
```py
Exception during loading of cog
Traceback (most recent call last):
  File "/home/discbot/red-venv/lib/python3.8/site-packages/redbot/core/core_commands.py", line 114, in _load
    await bot.load_extension(spec)
  File "/home/discbot/red-venv/lib/python3.8/site-packages/redbot/core/bot.py", line 801, in load_extension
    lib = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/discbot/red-venv/fkred/Red-DiscordBot/cogs/CogManager/cogs/updatechecker/__init__.py", line 1, in <module>
    from .updatechecker import UpdateChecker
  File "/home/discbot/red-venv/fkred/Red-DiscordBot/cogs/CogManager/cogs/updatechecker/updatechecker.py", line 16, in <module>
    class UpdateChecker(commands.Cog):
  File "/home/discbot/red-venv/fkred/Red-DiscordBot/cogs/CogManager/cogs/updatechecker/updatechecker.py", line 184, in UpdateChecker
    async def fetch_feed(self, url: str) -> Optional[feedparser.FeedParserDict]:
AttributeError: module 'feedparser' has no attribute 'FeedParserDict'
```

**Comment by ajwsert** [comment]
Yep, getting this error as well. I think it started after updating Red to 3.3.0.

**Comment by Dav-Git** [comment]
This seems to have fixed itself. However I'm a little disappointed with the support I've been getting so far.
